name: Cancel Victoria Saturday if running

on:
  workflow_dispatch:

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: ${{ github.workflow }}
          access_token: ${{ secrets.GITHUB_TOKEN }}
