name: Generate Dynamic Schedule

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight to update the schedule

jobs:
  generate-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: actions/checkout@v1
    - name: Setup git user
      run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Generate dynamic workflow
      run: python yamlcreater.py

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .github/workflows/dynamic_schedule.yml
        git commit -m 'Update dynamic schedule workflow'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
